---
# tasks file for common

 - name: Update all packages to latest version
   ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
        force_apt_get: yes
        dpkg_options: "force-confdef,force-confold"
        autoremove: yes
   environment:
        DEBIAN_FRONTEND: noninteractive

 - name: Install common utilities
   ansible.builtin.apt:
        name: "{{ common_packages }}"
        state: present
   notify: Restart affected services

 - name: Set timezone
   ansible.builtin.command: timedatectl set-timezone "{{ timezone }}"
   changed_when: false 

 - name: Verify timezone
   ansible.builtin.command: timedatectl
   register: tz_result
   changed_when: false

 - debug:
        msg: "Current timezone is {{ tz_result.stdout_lines | select('search', 'Time zone') | list }}"
