---
# tasks file for nginx-server
    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Ensure web root directory exists
      ansible.builtin.file:
        path: "{{ web_root }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Deploy Nginx configuration from template
      ansible.builtin.template:
        src: "../templates/nginx.conf.j2"
        dest: /etc/nginx/sites-available/custom_site.conf
        owner: root
        group: root
        mode: '0644'
      notify: Restart Nginx

    - name: Enable site by creating symlink
      ansible.builtin.file:
        src: /etc/nginx/sites-available/custom_site.conf
        dest: /etc/nginx/sites-enabled/custom_site.conf
        state: link
      notify: Restart Nginx

    - name: Remove default site if present
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: Restart Nginx


