---
# handlers file for common
 - name: Restart affected services
   service:
      name: "{{ item }}"
      state: restarted
   loop:
      - vim
      - wget
      - curl
      - git
      - htop
      - unzip
